# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{radiant-rbac_base-extension}
  s.version = "1.3.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Jim Gay"]
  s.date = %q{2010-07-05}
  s.description = %q{Flexible user role management for Radiant.}
  s.email = %q{jim@saturnflyer.com}
  s.extra_rdoc_files = [
    "README.markdown"
  ]
  s.files = [
    ".gitignore",
     "HELP_developer.md",
     "README.markdown",
     "Rakefile",
     "VERSION",
     "app/controllers/admin/roles_controller.rb",
     "app/helpers/admin/alterations_helper.rb",
     "app/helpers/admin/roles_helper.rb",
     "app/models/role.rb",
     "app/models/role_action_observer.rb",
     "app/models/role_user.rb",
     "app/views/admin/roles/_add_role_form.html.haml",
     "app/views/admin/roles/index.html.haml",
     "app/views/admin/roles/show.html.haml",
     "app/views/admin/users/preferences.html.haml",
     "config/locales/en.yml",
     "config/routes.rb",
     "cucumber.yml",
     "db/migrate/001_create_roles.rb",
     "db/migrate/002_create_role_users.rb",
     "db/migrate/003_setup_standard_roles.rb",
     "db/migrate/004_alter_roles.rb",
     "db/migrate/005_add_standard_role_details.rb",
     "db/migrate/006_add_user_info.rb",
     "db/migrate/20100705182511_rename_role_developer_to_designer.rb",
     "features/support/env.rb",
     "features/support/paths.rb",
     "lib/rbac_support.rb",
     "lib/tasks/rbac_base_extension_tasks.rake",
     "public/javascripts/rbac/admin/role_details.js",
     "public/stylesheets/rbac/rbac.css",
     "rbac_base_extension.rb",
     "spec/controllers/admin/roles_controller_spec.rb",
     "spec/controllers/admin/roles_routing_spec.rb",
     "spec/helpers/admin/roles_helper_spec.rb",
     "spec/models/role_spec.rb",
     "spec/models/user_spec.rb",
     "spec/spec.opts",
     "spec/spec_helper.rb",
     "spec/views/admin/roles/index_spec.rb",
     "spec/views/admin/roles/show_spec.rb"
  ]
  s.homepage = %q{http://github.com/saturnflyer/radiant-rbac_base-extension}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{RBAC Base Extension for Radiant CMS}
  s.test_files = [
    "spec/controllers/admin/roles_controller_spec.rb",
     "spec/controllers/admin/roles_routing_spec.rb",
     "spec/helpers/admin/roles_helper_spec.rb",
     "spec/models/role_spec.rb",
     "spec/models/user_spec.rb",
     "spec/spec_helper.rb",
     "spec/views/admin/roles/index_spec.rb",
     "spec/views/admin/roles/show_spec.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<radiant>, [">= 0.9"])
    else
      s.add_dependency(%q<radiant>, [">= 0.9"])
    end
  else
    s.add_dependency(%q<radiant>, [">= 0.9"])
  end
end

